### ISSUE TITLE
Update to use slightly-modified version of upstream cc_configure and fix build
Fix bootclasspaths and build warnings [phab:D1303]

### ISSUE THREAD

**Issue by kythebot** [google/kythe#1688]
_Created by **shahms** at 2017-02-03 01:59:04_: 

Partially fix build and test with bazel 0.4.4

**Comment by kythe** [comment]
_**zarko** wrote at 2017-02-03 05:25:57_:

test //... is failing on OS X:
```
ERROR: /private/var/tmp/_bazel_zarko/2be6994bf77f75bac8f1433eb6e9dc33/external/com_github_google_glog/BUILD.bazel:10:1: C++ compilation of rule 'com_github_google_glog//:glog' failed: Process exited with status 1 [sandboxed].
In file included from external/com_github_google_glog/src/signalhandler.cc:42:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ucontext.h:43:2: error: The deprecated ucontext routines require _XOPEN_SOURCE to be defined
#error The deprecated ucontext routines require _XOPEN_SOURCE to be defined
 ^
1 error generated.
Use --strategy=CppCompile=standalone to disable sandboxing for the failing actions.
```
This may be unrelated. `master` won't build with Bazel 0.4.4.

**Comment by kythe** [comment]
_**shahms** wrote at 2017-02-03 15:25:52_:

>>! In (earlier comment), zarko wrote:
> test //... is failing on OS X:
> ```
> ERROR: /private/var/tmp/_bazel_zarko/2be6994bf77f75bac8f1433eb6e9dc33/external/com_github_google_glog/BUILD.bazel:10:1: C++ compilation of rule 'com_github_google_glog//:glog' failed: Process exited with status 1 [sandboxed].
> In file included from external/com_github_google_glog/src/signalhandler.cc:42:
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ucontext.h:43:2: error: The deprecated ucontext routines require _XOPEN_SOURCE to be defined
> #error The deprecated ucontext routines require _XOPEN_SOURCE to be defined
>  ^
> 1 error generated.
> Use --strategy=CppCompile=standalone to disable sandboxing for the failing actions.
> ```
> This may be unrelated. `master` won't build with Bazel 0.4.4.

Thanks for taking a look on OS X.  This is probably related to the changes to `clang_configure.bzl`.  I can certainly dig into that more, although at this point my main focus is trying to figure out how/why the path munging broke for Java.

**Comment by kythe** [comment]
_**shahms** wrote at 2017-02-03 19:18:04_:

  - Add hacky workaround for path canonicalization changes in Java
  - Allow building with 0.4.3 as well
  - Add _XOPEN_SOURCE to fix build on OS X

# Updating (earlier comment): Update to use slightly-modified version of upstream cc_configure and fix build
Fix bootclasspaths and build warnings

**Comment by kythe** [comment]
_**shahms** wrote at 2017-02-03 19:22:36_:

  - Fix RUNPATH->JAVA_RUNFILES

# Updating (earlier comment): Update to use slightly-modified version of upstream cc_configure and fix build
Fix bootclasspaths and build warnings

**Comment by kythe** [comment]
_**shahms** wrote at 2017-02-03 19:23:25_:

PTAL; this should resolve the Java test issues and (hopefully) OS X.

**Comment by kythe** [comment]
_**salguarnieri** wrote at 2017-02-03 19:40:09_:

I'm on bazel 0.4.3 on OS X, but I get the following error with this patch

```
(git)-[arcpatch-(earlier comment) ]/kythe  bazel build //kythe/cxx/extractor/testdata:extract_verify_std_string_test
INFO: Found 1 target...
INFO: From CcIndexer kythe/cxx/extractor/testdata/extract_verify_std_string_test.compilation/kythe/cxx/extractor/testdata/extract_verify_std_string_test.cc.entries.gz:
In file included from /execroot/kythe/kythe/cxx/extractor/testdata/extract_verify_std_string_test.cc:1:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:435:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iosfwd:90:10: fatal error: 'wchar.h' file not found
#include <wchar.h>  // for mbstate_t
         ^
1 error generated.
Error: Errors during indexing.
ERROR: /kythe/cxx/extractor/testdata/BUILD:208:1: output 'kythe/cxx/extractor/testdata/extract_verify_std_string_test.compilation/kythe/cxx/extractor/testdata/extract_verify_std_string_test.cc.entries.gz' was not created.
ERROR: /kythe/cxx/extractor/testdata/BUILD:208:1: not all outputs were created or valid.
Target //kythe/cxx/extractor/testdata:extract_verify_std_string_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.978s, Critical Path: 1.40s
```

**Comment by kythe** [comment]
_**shahms** wrote at 2017-02-03 20:23:23_:

Thanks, Sal, I'll keep digging.

**Comment by kythe** [comment]
_**salguarnieri** wrote at 2017-02-05 07:00:33_:

It is possible that my OS X issues stem from warnings like the following during the build

```
ld: warning: direct access in function
  'clang::RecursiveASTVisitor<(anonymous namespace)::ASTPrinter>::TraverseDecl(clang::Decl*)'
  from file 'third_party/llvm/llvm/build/lib/libclangFrontend.a(ASTConsumers.cpp.o)'
  to global weak symbol
  'clang::TemplateTemplateParmDecl::getDefaultArgument() const::None'
  from file 'bazel-out/host/bin/kythe/cxx/indexer/cxx/liblib.a(IndexerASTHooks.o)'
  means the weak symbol cannot be overridden at runtime. This was likely caused by different
  translation units being compiled with different visibility settings.
```

**Comment by kythe** [comment]
_**shahms** wrote at 2017-02-06 16:11:03_:

That's actually a big help! It at least suggests that the issue is with differing cxx flags, rather than something else.  I'll keep digging.

**Comment by kythe** [comment]
_**salguarnieri** wrote at 2017-02-06 16:43:26_:

Things I tried (but didn't work)

* Upgrading to Xcode 8.3 beta & command line tools (the next version)
* Adding -Wl,-no_weak_imports to clang_configure's ld flags

I ran across similar errors from when people upgraded to 10.12 and the "latest" Xcode, but I couldn't figure out how/if their errors connected to ours.

I've been reproducing the test failure with `bazel test //kythe/cxx/indexer/cxx:test` but I don't remember that exact invocation triggering the weak symbol warnings.

**Comment by kythe** [comment]
_**shahms** wrote at 2017-02-06 21:47:54_:

  - Fallback to unadorned compiler name

# Updating (earlier comment): Update to use slightly-modified version of upstream cc_configure and fix build
Fix bootclasspaths and build warnings

**Comment by kythe** [comment]
_**shahms** wrote at 2017-02-06 22:29:49_:

  - Fix cc wrapper to use clang by default, not gcc

# Updating (earlier comment): Update to use slightly-modified version of upstream cc_configure and fix build
Fix bootclasspaths and build warnings

**Comment by kythe** [comment]
_**shahms** wrote at 2017-02-06 22:30:02_:

We were accidentally using gcc by default in the compiler wrapper script.  This update should fix the OS X build issues.

**Comment by kythe** [comment]
_**salguarnieri** wrote at 2017-02-06 22:36:47_:

Giving it a run through on my machine now

**Comment by kythe** [comment]
_**shahms** wrote at 2017-02-06 22:51:59_:

  - Fix error message to mention clang, not gcc

# Updating (earlier comment): Update to use slightly-modified version of upstream cc_configure and fix build
Fix bootclasspaths and build warnings

**Comment by kythe** [comment]
_**salguarnieri** commented inline (context lost during migration) at 2017-02-06 23:41:12_:

typo or have you tested w/ 0.4.3?

**Comment by kythe** [comment]
_**salguarnieri** commented inline (context lost during migration) at 2017-02-06 23:41:12_:

nit: can you add a todo/ticket to get rid of join_paths since I think the whole cmd_helper package is deprecated? https://bazel.build/versions/master/docs/skylark/lib/cmd_helper.html

**Comment by kythe** [comment]
_**salguarnieri** commented inline (context lost during migration) at 2017-02-06 23:41:12_:

Should this be $(basename ${BAZEL_CC}) to match above?

**Comment by kythe** [comment]
_**salguarnieri** wrote at 2017-02-06 23:41:12_:

LGTM -- We discussed offline that the fix for OS X is ongoing work but we wanted to get the linux fix out since it is ready.

**Comment by kythe** [comment]
_**salguarnieri** accepted this revision at 2017-02-06 23:41:12_

**Comment by kythe** [comment]
_**shahms** commented inline (context lost during migration) at 2017-02-06 23:45:25_:

Yeah, I've been testing with 0.4.3 as well.

**Comment by kythe** [comment]
_**shahms** commented inline (context lost during migration) at 2017-02-06 23:45:25_:

Done: #1696

**Comment by kythe** [comment]
_**shahms** commented inline (context lost during migration) at 2017-02-06 23:45:25_:

I think the full path is correct (and I suspect the above should be `$(dirname)/$(basename | sed)` as well.

**Comment by kythe** [comment]
_**shahms** closed via commit 088b53f57ae33629a930ab654b634550bc2b5115 at 2017-02-06 23:48:35_
