### ISSUE TITLE
Make sure kythe builds with clang 3.6 and in C++14 mode [phab:T21]

### ISSUE THREAD

**Issue by kythe** [google/kythe#228]
_Created by **tfarina** at 2015-02-06 00:53:44_: 

$ ./campfire build //kythe/cxx/indexer/cxx:all

kythe/cxx/common/index_pack.h:134:33: error: 'open_mode' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  IndexPackFilesystem::OpenMode open_mode() const { return open_mode_; }
                                ^
kythe/cxx/common/index_pack.h:112:20: note: overridden virtual function is here
  virtual OpenMode open_mode() const = 0;
                   ^
1 error generated.

kythe/cxx/indexer/cxx/KytheGraphObserver.h:147:8: error: 'recordFunctionNode' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  void recordFunctionNode(const NodeId &Node,
       ^
kythe/cxx/indexer/cxx/GraphObserver.h:251:16: note: overridden virtual function is here
  virtual void recordFunctionNode(const NodeId &Node,
               ^
In file included from kythe/cxx/indexer/cxx/KytheGraphObserver.cc:17:
kythe/cxx/indexer/cxx/KytheGraphObserver.h:150:8: error: 'recordCallableNode' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  void recordCallableNode(const NodeId &Node);
       ^
kythe/cxx/indexer/cxx/GraphObserver.h:264:16: note: overridden virtual function is here
  virtual void recordCallableNode(const NodeId &Node) {}
               ^
kythe/cxx/indexer/cxx/KytheGraphObserver.cc:611:30: error: no member named 'emplace' in 'std::map<clang::FileID, kythe::KytheClaimToken, std::less<clang::FileID>, std::allocator<std::pair<const clang::FileID, kythe::KytheClaimToken> > >'
        claim_checked_files_.emplace(file, token);
        ~~~~~~~~~~~~~~~~~~~~ ^
3 errors generated.

kythe/cxx/indexer/cxx/KytheIndexerUnitTest.cc:204:8: error: 'popFile' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  void popFile() {
       ^
kythe/cxx/indexer/cxx/GraphObserver.h:527:16: note: overridden virtual function is here
  virtual void popFile() {}
               ^
1 error generated.

**Comment by kythe** [comment]
_**shahms** wrote at 2015-05-22 18:24:22_:

Problems thus far encountered on "Ubuntu 14.04 LTS" with clang-3.6 -std=c++14:

1) libstdc++-4.8 <cstdio> has `using ::gets;` which has been removed in C++14
2) Installing and explicitly using libc++ (by modifying setup_bazel.sh and CROSSTOOL)
 a) crosstool config needs:
    cxx_flag: "-lc++"
    cxx_flag: "-stdlib=libc++"
    linker_flag: "-lm"
    linker_flag: "-lc++"
  b) setup_bazel.sh needs `-stdlib=libc++` to find/prefer non-gcc include paths
3) third_party/llvm/llvm/include/llvm/Support/Allocator.h:412:65: error: 'S' does not refer to a value
  this is in a call to `offsetof(S, x)` followed by an error that `x` doesn't refer to a name in scope.  I suspect offsetof() isn't the correct version?

**Comment by kythe** [comment]
_**shahms** wrote at 2015-05-22 21:06:31_:

I think using `libc++` is a deeper rathole than necessary, but using `-std=c++14` with `libstdc++-4.8` still breaks on `::gets` due to an incompatibility between `stdio.h` (which conditions its export of `::gets` on !C11 and C++ <= C++11) and `cstdio` (which unconditionally import `gets` into the `std` namespace via `using ::gets`).

It's a hack, but we could inject a suitable declaration ahead of the `stdio.h` import, but I'm not sure how to go about that.

**Comment by kythe** [comment]
_**shahms** wrote at 2015-05-26 16:54:05_:

With that workaround applied, clang-3.6 installed and CROSSTOOL configured appropriately, Kythe builds with clang-3.6 in c++14 mode.

**Comment by kythe** [comment]
commit ad51663b41e8d9d089681ea8d216d05528b85acb

**Comment by kythe** [comment]
revision #269
